module.exports.descriptors = [
    'Encantado',
    'Antiguo',
    'Petrificado',
    'Rugiente',
    'Hermoso',
    'Mortal',
    'Silencioso',
    'Ruidoso',
    'Tranquilo',
    'Ruby',
    'Nebuloso',
    'Paraíso',
    'De los 7 colores',
    'Nevado',
    'Soleado',
    'Lluvioso',
    'Polvoriento',
    'Diamante'
]

module.exports.places = [
    'Bosque',
    'Aldea',
    'Cañón',
    'Estanque',
    'Campamento en grupo',
    'Campamento de caballos',
    'Pueblo fantasma',
    'Campamento',
    'Campamento disperso',
    'Mar',
    'Río',
    'Arroyo',
    'Playón',
    'Terreno',
    'Manantial',
    'Orillón',
    'Cuevón',
    'Campamento de mulas',
    'Campamento de caza',
    'Acantilado',
    'Hueco'
]
